Repository nedbrek/Atlantis, pull requests merged in 2018-12, with the labels that each got.

#51 Disable Certain Monsters
  miskatonic/extra.cpp
  miskatonic/rules.cpp
Labels: Enhancement

#53 Multiple Hitch Items
  faction.cpp
  game.h
  genrules.cpp
  items.h
  miskatonic/gamedata.cpp
  modify.cpp
  standard/gamedata.cpp
  unit.cpp
Labels: Enhancement

#57 Standard/Miskatonic Armor Bug Fix and Stealth Changes
  miskatonic/gamedata.cpp
  miskatonic/rules.cpp
  standard/gamedata.cpp
  standard/rules.cpp
Labels: Bug, Enhancement

#59 Add period in Enters event
  game.h
  runorders.cpp
Labels: Bug

#60 Summon Wolves In Hills
  game.h
  skillshows.cpp
  spells.cpp
Labels: Enhancement

#61 Miskatonic Rulesset: Enabled USE_WEAPON_ARMOR_COMMAND
  miskatonic/rules.cpp
Labels: Enhancement

#62 Miskatonic Rulesset: Bow Changes and Monster Adjustment
  miskatonic/gamedata.cpp
  miskatonic/rules.cpp
Labels: Enhancement
