Repository nedbrek/Atlantis, pull requests merged in 2019-01, with the labels that each got.

#63 Fixes for PORTAL LORE
  game.h
  miskatonic/gamedata.cpp
  skillshows.cpp
  spells.cpp
  standard/gamedata.cpp
Labels: Bug, Enhancement

#64 Miskatonic Rulesset: Changed ARMY_ROUTE
  miskatonic/rules.cpp
Labels: Enhancement

#65 Fix for description of ENCHANT SWORDS
  game.h
  skillshows.cpp
Labels: Bug

#66 Fix for description of spell damage
  army.cpp
  army.h
  battle.cpp
  game.h
  miskatonic/gamedata.cpp
  specials.cpp
  standard/gamedata.cpp
Labels: Bug

#67 Fix for ENCHANT_SWORDS
  game.h
  spells.cpp
  spells.h
Labels: Bug

#69 Fix enchanted versions of bows
  game.h
  miskatonic/gamedata.cpp
Labels: Enhancement

#70 Miskatonic Rulesset: Monster Loot Balancing
  miskatonic/gamedata.cpp
  miskatonic/rules.cpp
Labels: Enhancement

#73 Fix #71 sharing description problem
  game.h
  unit.cpp
Labels: Bug

#75 Fix for descriptions of crossing levels and underworld
  game.h
  skillshows.cpp
Labels: Bug

#76 Fixed StartLoc command in players.in
  faction.cpp
  faction.h
  game.cpp
  game.h
  miskatonic/extra.cpp
  standard/extra.cpp
Labels: Bug

#78 Fix for raw materials with multiple man-months per output batch
  game.h
  monthorders.cpp
Labels: Bug
